version: "3"

services:
  app:
    build:
      context: .
      target: builder
    image: golang-learning
    volumes:
      - .:/app
    command: reflex -r '\.go$$' -s go run learning/golang
    # command: reflex -r '\.go$$' -s go run ./run
    ports:
      - "5000:8080"
    environment:
      - ENV=dev    
      